### ISSUE TITLE
Chat Bubble with NLC

### ISSUE THREAD

**Issue by omertarikkoc** [dmitrizzle/chat-bubble#45]
I really liked the repo but I didn't understand how can I connect this one with an NLC system such as Amazon Lex.

If it is possible can you provide a tutorial for us?

Thank you so much!

**Comment by dmitrizzle** [comment]
Will definitely make one soon!

**Comment by omertarikkoc** [comment]
Thank you so much! Looking forward to seeing one!

**Comment by dmitrizzle** [comment]
Hey @omertarik96 I've gotten sick and lost my voice so I'm just writing the steps down here for now. Please let me know if this makes sense - and if not how can I make it better. If it checks out I'll either do a proper post on Medium or a video later on when I can talk normally again.
***

## Request
In my use case I built a proxy on my back-end that processes the NLC requests. This way things are a bit simplified for me with added security. The request is simply sent as a `GET` variable, like so: `https://myserver.com/request?text=How%20hot%20will%20it%20be%20today%3F` (read: "How hot will it be today?").

I use IBM Watson services which are quite easy to implement and train but it does require some time and effort. There's a nice getting-started guide for Watson NLC [here](https://medium.com/archieai/give-your-product-ai-powered-wings-19427eafecb2). Keep in mind that when you train it your class names should match your JSON answer script keys.

## Response
From my back-end I forward the request to Watson along with the credentials required to process it (id, passphrase). What the back-end recieves get back from IBM is usually a JSON object, that looks something like this (this is straight from their [docs](https://www.ibm.com/watson/developercloud/natural-language-classifier/api/v1/curl.html?curl#classify)):
```javascript
{
  "classifier_id" : "10D41B-nlc-1",
  "url" : "https://gateway.watsonplatform.net/natural-language-classifier/api/v1/classifiers/10D41B-nlc-1/classify?text=How%20hot%20wil/10D41B-nlc-1",
  "text" : "How hot will it be today?",
  "top_class" : "temperature",
  "classes" : [ {
    "class_name" : "temperature",
    "confidence" : 0.9998201258549781
  }, {
    "class_name" : "conditions",
    "confidence" : 1.7987414502176904E-4
  } ]
}
```
I go through it on the server and toss things that I won't be using, ending up with:
```javascript
{
    "top_class": "temperature"
}
```
The above is basically what `https://myserver.com/request?...` will return every time. Front-end shouldn't have to deal with all the extra crap. My back-end takes care of minimum match threshold (confidence level) and returns `{"top_class":"fail"}` should it happen to be too low: for a custom "I don't get it" message.

## Sending requests with `chat-bubble`
With NLC setup out of the way we'll need to get our JavaScript to communicate with the server. We'll need to use Ajax. `chat-bubble` is a vanilla JS script so in this example I'll assume you are using [this helper script](https://gist.github.com/dmitrizzle/af8b179283294b17b8ff59efd7148bfe) that does nothing more special than cut down time for writing `XMLHttpRequest()` stuff.

## Setting up `chat-bubble`
If you've tried following an [example with keyboard input](https://github.com/dmitrizzle/chat-bubble/blob/master/component/examples/4-advanced-keyboard.html) everything should be straight-forward from here on. We have the same JSON object that lists all possible replies with indexes. All we need to do is modify `inputCallbackFn(object)` to send Ajax requests and receive class id that would correspond with one of the objects in our script:
```javascript
// set up the chatbot script
var givemeBubbles = new Bubbles(
  document.getElementById('chat'),
  "givemeBubbles",
  {
    inputCallbackFn: function(object){
      // the `object` variable will contain the following data:
      // { input: "what user has typed"
      // convo: "a copy of your JSON script for all the answers",
      // standingAnswer: "a reference for the last given answer, 
      // should you need to restart from there" }
    }
  }
);
givemeBubbles.talk(convo);
```

## Attaching the NLC service
Our last step would be attaching the Ajax request handler and connecting the wires:
```javascript
var givemeBubbles = new Bubbles(
  document.getElementById('chat'),
  "givemeBubbles",
  {
    inputCallbackFn: function(object){
      // sending the request with url-encoded text string
      Ajax("https://myserver.com/request?text=" + encodeURI(o.input), function(data){
          // our return `data` should contain `top_class` (from your Watson training list)
          // which would match one of the answers in your JSON script
          givemeBubbles.talk(object.convo, data.top_class)
      })
    }
  }
);
givemeBubbles.talk(convo);
```

## Further steps
This is just the basics, but you may want to consider handling errors (i.e. what happens if your classifier fails or takes too long?). Also, as in the case in my application having a JSON object of static answers was not feasible as most bot responses were dynamic, so I built another service that would fetch a specific answer from the back-end every time.

I hope this helps rather than confuses you! Do let me know if I can improve this answer for you.

**Comment by omertarikkoc** [comment]
Thank you so much! I haven't had time to try but definitely, I will!

Also, [my personal portfolio with chat-bubble](https://omertarikkoc.com) is ready. Please check it out, I need your feedback :)

**Comment by dmitrizzle** [comment]
Nice portfolio, man! Would love to see it work with NLC as well 😉

**Comment by omertarikkoc** [comment]
Yes, my next update will be working with NLC 😄

**Comment by dmitrizzle** [comment]
This issue shall be a reference for #38, but I'll have it closed is I believe the question has been answered.
