### ISSUE TITLE
Toggle Text Input

### ISSUE THREAD

**Issue by JensThanx** [dmitrizzle/chat-bubble#58]
It would be great if the text input could simply toggled on/off. Depending on the dialog it might sometimes make sense to only allow limited choices and sometimes to allow text input. Or is it already possible, e.g. by passing in a "inputCallbackFn" to my "Bubbles" object or by setting it to "null"?

**Comment by dmitrizzle** [comment]
I've never tried doing that, but perhaps `inputCallbackFn` can do just that!

**Comment by JensThanx** [comment]
If I call the "typeInput" function the text input field indeed appears. But passing (null) e.g. only creates another text input field on top. So it is somewhat safe to do so. Probably "typeInput" should not even be exposed to the outside.

**Comment by dmitrizzle** [comment]
I think a better way may be initializing `inputCallbackFn` as in the example `3-keyboard-input.html` and use `inputCallbackFn` to either show or hide it with CSS. Because `typeInput` function is used to initialize the input component, which also requires an input processor function - meaning that it should ever be called only once to set things up; once it's there it should just work.

If you are to do this with CSS, there should be no issues as duplicating keyboard input or non-functioning keyboard input.

**Comment by JensThanx** [comment]
True. It is rather a matter of visibility.

**Comment by dmitrizzle** [comment]
Cool! I'll mark it solved, we can re-open this ticket if necessary in the future 👍
