### ISSUE TITLE
How to not show any option for the user and only let him type the question ?

### ISSUE THREAD

**Issue by hamzaLeb** [dmitrizzle/chat-bubble#64]
I don't know how to delete the user options (example: banana, ice cream) and instead just let him type in the question. I tried to delete 'question' from 'reply' part, replace it with null, with empty string ... but no one seems to work. Can you help me out with it please ?
Thank you

**Comment by JensThanx** [comment]
Hi hamzaLeb. I see your point. I thought it would be easy, but I guess it is not. Maybe @dmitrizzle also has some good ideas ;)

However, with a few adjustments I found that it can be done. 

Check the example-3 (which you have surely used so far). In line 75 I see the comment "search function". This is where the program tries to find a valid answer from the list of answers. If it does not find any answer, it calls the "miss()" function.

I would try to **either** change the "search function" itself, so that it does not try to find a valid answer from the list of answers, but from the list of dialog elements (try this, it worked for me):
`    // search function
    var found = false
    Object.keys(o.convo).forEach(function(e, i) {
      e.includes(strip(o.input)) && o.input.length > 0
        ? (found = o.input)
        : found ? null : (found = false)
    })
    found ? match(found) : miss()`

**Or** you could would try to change the "miss()" function. You could maybe pass the "o.input" (the user input) and then use this inside the "miss()" function to check if there is a valid answer available. 

Either way, you can then remove the "reply" part, which you do not want to show, completely.
I hope this will point you into the right direction.

**Comment by dmitrizzle** [comment]
The way I achieved skipping reply buttons in one of my earlier implementations is by not having reply objects at all. In my use case I've connected the bot to Watson NLC and used Watson to take care of all possible replies during Ajax calls.

It seems that in your case you are trying to achieve a similar task but without the NLC component.

Because this tool uses browser DOM to store state, there isn't a simple/supported solution to hide the response bubbles with API. I wouldn't recommend this either since you are very likely making your users' life harder by not giving them the precise options to choose from, while the built-in keyword search functionality relies on precise input. When using NLC, the machine learning part would at least allow users to have various phrasings and typos.

Anyways, I'd suggest you simply alter the CSS to hide the answer bubbles. That way you won't have to worry about dealing with JavaScript: https://github.com/dmitrizzle/chat-bubble/blob/master/component/styles/reply.css - you can try `display:none` or `visibility:hidden`.

Hope this helps!

**Comment by hamzaLeb** [comment]
Thank you @JensThanx  and @dmitrizzle for your support. The suggested ideas worked for me, I chose to completely remove the reply part. Thanks for the support 👍
