### ISSUE TITLE
Just wanted to ask a question

### ISSUE THREAD

**Issue by lexfefegha** [dmitrizzle/chat-bubble#70]
I am currently using chat-bubble to teach how to prototype bot conversations. I wanted to ask where in bubbles.js - could I change 'says, reply, question and answer' so I could make it easier for others who may not have coding competency to understand what those mean in the index.html. 

For example, changing 'says' to 'bot_says'

**Comment by dmitrizzle** [comment]
That's fantastic! 

The easiest way would be to search for keyword "says" in the code and change it. Currently it's here: https://github.com/dmitrizzle/chat-bubble/blob/master/component/Bubbles.js#L158

When changing "reply" please pay attention not to make the same change to CSS-related code, if you do, you'll have to do the same in the CSS files.

Just pay attention to change the variable name directly, rather than a part of a variable, i.e. `standingAnswer` is not the same as `answer`

**Comment by lexfefegha** [comment]
thank you for your swift response! made those changes

made changes to reply but seem to be getting a bug when pressing a button, it doesn't move on, it just breaks - https://glitch.com/edit/#!/feminist-chatbot?path=component/js/Bubbles.js:1:0

**Comment by dmitrizzle** [comment]
I'm seeing `Bubbles.js:272 Uncaught ReferenceError: reply is not defined` error in browser console. Seems like you'll need to change `interactionsSave(say, reply)` to `interactionsSave(say, human_reply)`. There may be other issues there as well, I recommend checking your browser console when making changes, it's usually quite helpful to find bugs.

**Comment by lexfefegha** [comment]
thank you, I will definitely use console to check changes!

**Comment by dmitrizzle** [comment]
It's been a while since this question was asked, I'll assume it's been sufficiently covered.
