### ISSUE TITLE
(rasa example) how do I get rid of the placeholder message : "Hi" ?

### ISSUE THREAD

**Issue by ilyasjamil** [dmitrizzle/chat-bubble#95]
I want the user to start the conversation, I dont want the message "Hi" to show up before the user types anything. How do I do that?

**Comment by dmitrizzle** [comment]
I think you need to have some sort of a prompt message from the chatbot at the beginning. But it's easy to modify what this message is. In the RASA example, simply change this line: https://github.com/dmitrizzle/chat-bubble/blob/master/examples/7-nlc-rasa.html#L216

If you want it to say nothing, you may need to fork this repo and modify the internals around here: https://github.com/dmitrizzle/chat-bubble/blob/master/component/Bubbles.js#L134 -- if you do that and manage to create an API for that case, I'd very much appreciate a PR so that everyone can benefit form that feature :)
