### ISSUE TITLE
What happened to Archie.io

### ISSUE THREAD

**Issue by saikarthikp9** [dmitrizzle/chat-bubble#98]
### Bug or feature request?
feature

### If it's a bug, please provide the full method to reproduce.
NA

PS. What happened to archie.io? btw.

**Comment by dmitrizzle** [comment]
Hey @saikarthikp9, I no longer work at that company but I still occasionally use and support this project personally. Because it has no dependencies, it's still safe to use as it relies on good ol' JavaScript. I may be pushing some updates and improvements to the repo this week.

I noticed that you were interested in implementing Google OAuth with `chat-bubble`. This implementation is up to your web app to handle, `chat-bubble` is just a front-end UI that can render your conversations for you.
